require("dotenv").config();

const m = require("masto");

const masto = m.createRestAPIClient({
  url: "https://networked-media.itp.io/",
  accessToken: process.env.TOKEN,
});

async function makeStatus(text) {
  const status = await masto.v1.statuses.create({
    status: text,
    visibility: "public",
  });
  console.log(status.url);
}
let emo = [
  "(＾▽＾)",
  "(๑>◡<๑)",
  "(o^▽^o)",
  "(≧◡≦)",
  "(^‿^)",
  "(◕‿◕)",
  "(≧ω≦)",
  "(*≧∀≦*)",
  "(*´▽｀*)",
  "(ノ´∀｀*)",
  "٩(๑> ₃ <)۶",
  "(✿◕‿◕)",
  "(´｡• ᵕ •｡`)",
  "♡",
  "(っ˘ω˘ς )",
  "(๑˃̵ᴗ˂̵)و",
  "(°▽°)",
  "(⁎˃ᆺ˂)",
  "(๑•͈ᴗ•͈)",
  "(ฅ^ω^)",
  "ヽ(*≧ω≦)ﾉ",
  "o(≧∀≦)o",
  "(*≧ω≦)",
  "(๑´ڡ`๑)",
  "(*≧︶≦))",
  "(￣▽￣)",
  "(๑´•.̫ • `๑)",
  "(*＾3＾)",
  "(✿´‿`)",
  "(๑˃̵ᴗ˂̵)",
  "(¬‿¬)",
  "( ͡° ͜ʖ ͡°)",
  "(｀∀´)",
  "(￣▽￣)",
  "(•̀ᴗ•́)",
  "(¬‿¬)",
  "( ＾◡＾)",
  "( ￣ー￣)",
  "(¬_¬)",
  "(๑>ᴗ<๑)",
  "( ᕙ(⇀‸↼‶)ᕗ )",
  "(¬‿¬ )",
  "(＾◇＾)",
  "(￣ω￣)",
  "(°ー°〃)",
  "(✧≖ ͜ʖ≖)",
  "(¬‿¬)",
  "( •̀ ω •́ )✧",
  "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧",
  "(￣ー￣)",
  "( ˘ ³˘)♥",
  "(◕‿◕)",
  "(˵ ͡° ͜ʖ ͡°˵)",
  "(￣ω￣)",
  "(๑˃̵ᴗ˂̵)",
  "(⁀⊙ω⊙⁀)",
  "(¬‿¬)",
  "(⁀ᗢ⁀)",
  "(๑•̀ㅂ•́)و✧",
  "(✧ω✧)",
];
let poems = [
  "STRAY birds of summer come to my window to sing and fly away. And yellow leaves of autumn, which have no songs, flutter and fall there with a sigh.",
  "O TROUPE of little vagrants of the world, leave your footprints in my words.",
  "THE world puts off its mask of vastness to its lover. It becomes small as one song, as one kiss of the eternal.",
  "IT is the tears of the earth that keep her smiles in bloom.",
  "THE mighty desert is burning for the love of a blade of grass who shakes her head and laughs and flies away.",
  "IF you shed tears when you miss the sun, you also miss the stars.",
  "THE sands in your way beg for your song and your movement, dancing water. Will you carry the burden of their lameness?",
  "HER wistful face haunts my dreams like the rain at night.",
  "ONCE we dreamt that we were strangers. We wake up to find that we were dear to each other.",
  "SORROW is hushed into peace in my heart like the evening among the silent trees.",
  "SOME unseen fingers, like idle breeze, are playing upon my heart the music of the ripples.",
  `"WHAT language is thine, O sea?" "The language of eternal question." "What language is thy answer, O sky?" "The language of eternal silence."`,
  "LISTEN, my heart, to the whispers of the world with which it makes love to you.",
  "THE mystery of creation is like the darkness of night--it is great. Delusions of knowledge are like the fog of the morning.",
  "DO not seat your love upon a precipice because it is high.",
  "I SIT at my window this morning where the world like a passer-by stops for a moment, nods to me and goes.",
  "THESE little thoughts are the rustle of leaves; they have their whisper of joy in my mind.",
  "WHAT you are you do not see, what you see is your shadow.",
  "MY wishes are fools, they shout across thy songs, my Master. Let me but listen.",
  "I CANNOT choose the best. The best chooses me.",
  "THEY throw their shadows before them who carry their lantern on their back.",
  "THAT I exist is a perpetual surprise which is life.",
  `"WE, the rustling leaves, have a voice that answers the storms, but who are you so silent?" "I am a mere flower."`,
  "REST belongs to the work as the eyelids to the eyes.",
  "MAN is a born child, his power is the power of growth.",
  "GOD expects answers for the flowers he sends us, not for the sun and the earth.",
  "THE light that plays, like a naked child, among the green leaves happily knows not that man can lie.",
  "O BEAUTY, find thyself in love, not in the flattery of thy mirror.",
  `MY heart beats her waves at the shore of the world and writes upon it her signature in tears with the words, "I love thee."`,
  `"MOON, for what do you wait?" "To salute the sun for whom I must make way."`,
  "THE trees come up to my window like the yearning voice of the dumb earth.",
  "HIS own mornings are new surprises to God.",
  "LIFE finds its wealth by the claims of the world, and its worth by the claims of love.",
  "THE dry river-bed finds no thanks for its past.",
  "THE bird wishes it were a cloud. The cloud wishes it were a bird.",
  `"THE waterfall sings, 'I find my song, when I find my freedom.'"`,
  "I CANNOT tell why this heart languishes in silence. It is for small needs it never asks, or knows or remembers.",
  "WOMAN, when you move about in your household service your limbs sing like a hill stream among its pebbles.",
  "THE sun goes to cross the Western sea, leaving its last salutation to the East.",
  "DO not blame your food because you have no appetite.",
  "THE trees, like the longings of the earth, stand a-tiptoe to peep at the heaven.",
  "YOU smiled and talked to me of nothing and I felt that for this I had been waiting long.",
  "THE fish in the water is silent, the animal on the earth is noisy, the bird in the air is singing, But Man has in him the silence of the sea, the noise of the earth and the music of the air.",
  "THE world rushes on over the strings of the lingering heart making the music of sadness.",
  "HE has made his weapons his gods. When his weapons win he is defeated himself.",
  "GOD finds himself by creating.",
  "SHADOW, with her veil drawn, follows Light in secret meekness, with her silent steps of love.",
  "THE stars are not afraid to appear like fireflies.",
  "I THANK thee that I am none of the wheels of power but I am one with the living creatures that are crushed by it.",
  "THE mind, sharp but not broad, sticks at every point but does not move.",
  "YOUR idol is shattered in the dust to prove that God's dust is greater than your idol.",
  "MAN does not reveal himself in his history, he struggles up through it.",
  `"WHILE the glass lamp rebukes the earthen for calling it cousin, the moon rises, and the glass lamp, with a bland smile, calls her, 'My dear, dear sister.'"`,
  "LIKE the meeting of the seagulls and the waves we meet and come near. The seagulls fly off, the waves roll away and we depart.",
  "MY day is done, and I am like a boat drawn on the beach, listening to the dance-music of the tide in the evening.",
  "LIFE is given to us, we earn it by giving it.",
  "WE come nearest to the great when we are great in humility.",
  "THE sparrow is sorry for the peacock at the burden of its tail.",
  "NEVER be afraid of the moments--thus sings the voice of the everlasting.",
  "THE hurricane seeks the shortest road by the no-road, and suddenly ends its search in the Nowhere.",
  "TAKE my wine in my own cup, friend. It loses its wreath of foam when poured into that of others.",
  "THE Perfect decks itself in beauty for the love of the Imperfect.",
  "GOD says to man, 'I heal you therefore I hurt, love you therefore punish.'",
  "THANK the flame for its light, but do not forget the lampholder standing in the shade with constancy of patience.",
  "TINY grass, your steps are small, but you possess the earth under your tread.",
  "THE infant flower opens its bud and cries, 'Dear World, please do not fade.'",
  "GOD grows weary of great kingdoms, but never of little flowers.",
  "WRONG cannot afford defeat but Right can.",
  "I GIVE my whole water in joy, sings the waterfall, 'though little of it is enough for the thirsty.'",
  "WHERE is the fountain that throws up these flowers in a ceaseless outbreak of ecstasy?",
  "THE woodcutter's axe begged for its handle from the tree. The tree gave it.",
  "IN my solitude of heart I feel the sigh of this widowed evening veiled with mist and rain.",
  "CHASTITY is a wealth that comes from abundance of love.",
  "THE mist, like love, plays upon the heart of the hills and brings out surprises of beauty.",
  "WE read the world wrong and say that it deceives us.",
  "THE poet wind is out over the sea and the forest to seek his own voice.",
  "EVERY child comes with the message that God is not yet discouraged of man.",
  "THE grass seeks her crowd in the earth. The tree seeks his solitude of the sky.",
  "MAN barricades against himself.",
  "YOUR voice, my friend, wanders in my heart, like the muffled sound of the sea among these listening pines.",
  "WHAT is this unseen flame of darkness whose sparks are the stars?",
  "LET life be beautiful like summer flowers and death like autumn leaves.",
  "HE who wants to do good knocks at the gate; he who loves finds the gate open.",
  "IN death the many becomes one; in life the one becomes many. Religion will be one when God is dead.",
  "THE artist is the lover of Nature, therefore he is her slave and her master.",
  "HOW far are you from me, O Fruit? 'I am hidden in your heart, O Flower.'",
  "THIS longing is for the one who is felt in the dark, but not seen in the day.",
  "YOU are the big drop of dew under the lotus leaf, I am the smaller one on its upper side, said the dewdrop to the lake.",
  "THE scabbard is content to be dull when it protects the keenness of the sword.",
  "IN darkness the One appears as uniform; in the light the One appears as manifold.",
  "THE great earth makes herself hospitable with the help of the grass.",
  "THE birth and death of the leaves are the rapid whirls of the eddy whose wider circles move slowly among stars.",
  "POWER said to the world, 'You are mine.' The world kept it prisoner on her throne. Love said to the world, 'I am thine.' The world gave it the freedom of her house.",
  "THE mist is like the earth's desire. It hides the sun for whom she cries.",
  "BE still, my heart, these great trees are prayers.",
  "THE noise of the moment scoffs at the music of the Eternal.",
  "I THINK of other ages that floated upon the stream of life and love and death and are forgotten, and I feel the freedom of passing away.",
  "THE sadness of my soul is her bride's veil. It waits to be lifted in the night.",
  "DEATH'S stamp gives value to the coin of life; making it possible to buy with life what is truly precious.",
  "THE cloud stood humbly in a corner of the sky. The morning crowned it with splendour.",
  "THE dust receives insult and in return offers her flowers.",
  "DO not linger to gather flowers to keep them, but walk on, for flowers will keep themselves blooming all your way.",
  "ROOTS are the branches down in the earth. Branches are roots in the air.",
  "THE music of the far-away summer flutters around the Autumn seeking its former nest.",
  "DO not insult your friend by lending him merits from your own pocket.",
  "THE touch of the nameless days clings to my heart like mosses round the old tree.",
  "THE echo mocks her origin to prove she is the original.",
  "GOD is ashamed when the prosperous boasts of His special favour.",
  "I CAST my own shadow upon my path, because I have a lamp that has not been lighted.",
  "MAN goes into the noisy crowd to drown his own clamour of silence.",
  "THAT which ends in exhaustion is death, but the perfect ending is in the endless.",
  "THE sun has his simple robe of light. The clouds are decked with gorgeousness.",
  "THE hills are like shouts of children who raise their arms, trying to catch stars.",
  "THE road is lonely in its crowd for it is not loved.",
  "THE power that boasts of its mischiefs is laughed at by the yellow leaves that fall, and clouds that pass by.",
  "THE earth hums to me today in the sun, like a woman at her spinning, some ballad of the ancient time in a forgotten tongue.",
  "THE grass-blade is worth of the great world where it grows.",
  "DREAM is a wife who must talk. Sleep is a husband who silently suffers.",
  "THE night kisses the fading day whispering to his ear, 'I am death, your mother. I am to give you fresh birth.'",
  "I FEEL, thy beauty, dark night, like that of the loved woman when she has put out the lamp.",
  "I CARRY in my world that flourishes the worlds that have failed.",
  "DEAR friend, I feel the silence of your great thoughts of many a deepening eventide on this beach when I listen to these waves.",
  "THE bird thinks it is an act of kindness to give the fish a lift in the air.",
  "IN the moon thou sendest thy love letters to me, said the night to the sun. 'I leave my answers in tears upon the grass.'",
  "THE Great is a born child; when he dies he gives his great childhood to the world.",
  "NOT hammerstrokes, but dance of the water sings the pebbles into perfection.",
  "BEES sip honey from flowers and hum their thanks when they leave. The gaudy butterfly is sure that the flowers owe thanks to him.",
  "TO be outspoken is easy when you do not wait to speak the complete truth.",
  "ASKS the Possible to the Impossible, 'Where is your dwelling place?' 'In the dreams of the impotent,' comes the answer.",
  "IF you shut your door to all errors, truth will be shut out.",
  "LEISURE in its activity is work. The stillness of the sea stirs in waves.",
  "THE leaf becomes flower when it loves. The flower becomes fruit when it worships.",
  "THE roots below the earth claim no rewards for making the branches fruitful.",
  "THIS rainy evening the wind is restless. I look at the swaying branches and ponder over the greatness of all things.",
  "STORM of midnight, like a giant child awakened in the untimely dark, has begun to play and shout.",
  "THOU raisest thy waves vainly to follow thy lover. O sea, thou lonely bride of the storm.",
];
let current = 0;
setInterval(() => {
  let intro =
    "*Stray Birds* is a famous collection of short, philosophical poems by Tagore, and it is also my favorite.";
  let rand = Math.floor(Math.random() * emo.length);
  let emoji = emo[rand];

  let content = intro + "\n\n";

  for (let i = 0; i < 2; i++) {
    content +=  poems[(current + i) % poems.length] + "\n\n";
  }

  content += emoji;

  makeStatus(content);

  current = (current + 2) % poems.length;
}, 1800000);
